apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.name }}
  labels:
    app: {{ .Values.labels.app }}
    version: {{ .Values.labels.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.strategy | nindent 12 }}
  selector:
    matchLabels:
       version: {{ .Values.labels.version }}
  template:
    metadata:
      labels: 
       version: {{ .Values.labels.version }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: {{ .Values.ports.name }}
              containerPort: {{ .Values.ports.containerPort }}
              protocol:  {{ .Values.ports.Protocol }}
          resources:
             {{- toYaml .Values.resources | nindent 12 }}






